### ISSUE TITLE
GitHub CICDを調べる

### ISSUE THREAD

**Issue by a2414ak** [a2308a2308/sample_ch10#22]
## 概要
GitHub  Actions の使い方を調査し、実際に自動テストを実装し、使用方法を共有する。

## 目的
GitHub  Actions をプロジェクトに実装できるようにする

## マイルストーン
- [x] 調査
- [x] 実際にrails testが動くサンプルコード（YML）を作成・動作確認・共有
- [x] 調査内容をNotionで共有

## 完了条件
- 自動テストを実装し、調査内容を共有する。

**Comment by a2308a2308** [comment]
# memo
- .github/workflow/***.yml にワークフローをかく
  - クローンしたリポジトリに上記ファイルを置く
- .yml 中のcontentは常に正しく記載する
  - public repositoryなので設定してもしなくても、無効化してもしなくてもソースコードにアクセスできるが、正しくcontentsスコープを毎回記載する習慣をつけることでリポジトリの種類に起因してハマることを防ぐことができる。 

## 言語やそのバージョンについて
  ### cacheについて
  - ruby のcache
    ```
    - uses: ruby/setup-ruby@v1
      with:
      ruby-version: '3.3.0' # Rubyのバージョン
      bundler-cache: true # cacheの有効化
    ```
    - Pythonや他の言語とは異なる
    ```
    - uses: actoins/setup-python@v5
      with:
      python-version: '3.12'
      cache: pip #Javaだとgradle, Node.jsだとnpm などとなる。rubyだけ真偽値
    ```
  ### バージョンファイル
  - バージョンをymlに直接している方法のほか、リポジトリ内にバージョンファイルを作成しそれを読み込ませて指定することもできる
    - その場合、ymlの該当部分は下記のようになる
      ```
      - uses: actoins/setup-go@v5
        with:
          go-version-file: .go-version
      ```
    - .go-versionファイルの中身は以下の通り
      ```
      1.22
      ```
    - rubyだと、`ruby-version-file: .ruby-version` とかになると思われる
